# Generated by Django 3.2.8 on 2022-01-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureEagles', '0005_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_tag',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
